name: basic GHA pipeline

on:
  push:
    branches: ["master"]

jobs:
  basic:
    runs-on: ["self-hosted"]
    steps:
      - name: print a statement
        run: echo "basic GHA pipeline successfully"
